client:
  ssl:
    one-way-authentication-enabled: false
    two-way-authentication-enabled: true
    key-store: clientidentity.jks
    key-password: secret
    key-store-password: secret
    trust-store: client-truststore.jks
    trust-store-password: secret